#%RAML 1.0

title: IDM Connect API
version: v1.0

types:
  contract: !include contract.json
  contracts: !include contracts.json

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/idm-connect:
  /contract:
    get:
      is: [
        searchable: {description: "", example: ""},
        pageable
      ]
    type:
      collection:
        schemaCollection: contracts
        schemaItem: contract
        exampleCollection: !include examples/contracts.json
        exampleItem: !include examples/contract.json
    /{id}:
      type:
        collection-item:
          schema: contract
          exampleItem: !include examples/contract.json
  /searchidm:
    description: Query external IDM system for existing users
    get:
      queryParameters:
        firstname:
          description: Users first name
          example: John
        lastname:
          description: Users last name
          example: Doe
        dateOfBirth:
          description: Users date of birth
          example: 2015-12-24
      responses:
        200:
          description: IDM returned OK
          body:
            application/json:
        400:
          description: IDM returned Bad Request
          body:
            application/json:
        401:
          description: IDM returned Unauthorized
          body:
            application/json:
        500:
          description: Internal server error
          body:
            text/plain: